data <- read.table("C:/Users/Desktop/household_power_consumption.txt", sep=";", header=TRUE, stringsAsFactors = FALSE)
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
subset_data <- subset(data, Date %in% c("2007-02-01", "2007-02-02"))
subset_data$Global_active_power <- as.numeric(subset_data$Global_active_power)
png("C:/Users/Desktop/plot1.png", width = 480, height = 480)
hist(subset_data$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col = "red")
dev.off()
